// Deterministic Spanish subjunctive lexicon + the mood-annotation post-pass.
//
// Shared by the chunk-and-gloss Edge Function (imported as
// '../_shared/subjunctive.ts') and the client test suite (imported from src/
// without the extension). Pure data + pure functions only — no Deno or DOM
// APIs, no imports — so both runtimes can load it unchanged. Unlike the prompt
// in src/prompt.ts, this is NOT duplicated: there is one copy.
//
// What it does:
//   1. Generates subjunctive conjugation tables per lemma: present, imperfect
//      (-ra and -se), perfect and pluperfect (-ra and -se), with person/number
//      for each form. Regular verbs are generated by rule (including the
//      c→qu / g→gu / z→c / g→j / c→zc spelling changes); stem-changers carry a
//      class flag; true irregulars live in a table.
//   2. Vetoes model `subjunctive_verb` tags whose token is not a subjunctive
//      form of the lemma the model named (task item 4).
//   3. Resolves the model's uncertain tags into `subjunctive_verb` (unambiguous
//      lexicon match) or `possible_subjunctive` (a homograph) (item 3).
//   4. Pre-scans Spanish input for forms the lexicon is sure about, so they can
//      be handed to the gloss prompt as given facts (item 5).
//
// Coverage: generation works for any regular-shaped lemma the model names, so
// the veto (which always has a model lemma) is broad. Reverse lookup — finding
// forms in text with no lemma given — only covers KNOWN_VERBS below, because a
// guessed lemma can't be verified. Tokens outside that list are "outside
// lexicon coverage" in the sense of the task doc: the model glosses them alone.

export type SubjTense =
  | 'present'
  | 'imperfect-ra'
  | 'imperfect-se'
  | 'perfect'
  | 'pluperfect-ra'
  | 'pluperfect-se';

export type PersonNumber = '1sg' | '2sg' | '3sg' | '1pl' | '2pl' | '3pl';

const PERSONS: ReadonlyArray<PersonNumber> = ['1sg', '2sg', '3sg', '1pl', '2pl', '3pl'];

export interface SubjForm {
  readonly form: string;
  readonly lemma: string;
  readonly tense: SubjTense;
  readonly person: PersonNumber;
}

// A span matched against the lexicon. `persons` has more than one entry when
// the form is shared (hable = 1sg and 3sg).
export interface SubjMatch {
  readonly lemma: string;
  readonly tense: SubjTense;
  readonly persons: ReadonlyArray<PersonNumber>;
}

// ===== Verb specs =====

// Stem-change class. 'ie-i' / 'ue-u' are the -ir verbs whose nosotros/vosotros
// forms and 3rd-person preterite also change (sentir → sintamos, sintieron).
type StemChange = 'none' | 'ie' | 'ue' | 'i' | 'ie-i' | 'ue-u';

interface VerbSpec {
  readonly lemma: string;
  readonly stemChange: StemChange;
  // enviar → envíe, continuar → continúe, aullar → aúlle: the weak vowel of the
  // stem takes a written accent in the stressed (boot) forms.
  readonly accented: boolean;
  // Irregular yo-stem, used for every present-subjunctive person (tener → teng-).
  readonly presentStem?: string;
  // Six fully irregular present-subjunctive forms (ser → sea …).
  readonly presentForms?: ReadonlyArray<string>;
  // Irregular 3rd-plural preterite; the imperfect subjunctive is built from it.
  readonly pret3pl?: string;
  readonly participles?: ReadonlyArray<string>;
}

type IrregularEntry = Omit<VerbSpec, 'lemma' | 'stemChange' | 'accented'> & {
  readonly stemChange?: StemChange;
};

const IRREGULAR: Readonly<Record<string, IrregularEntry>> = {
  ser: {
    presentForms: ['sea', 'seas', 'sea', 'seamos', 'seáis', 'sean'],
    pret3pl: 'fueron',
    participles: ['sido'],
  },
  ir: {
    presentForms: ['vaya', 'vayas', 'vaya', 'vayamos', 'vayáis', 'vayan'],
    pret3pl: 'fueron',
    participles: ['ido'],
  },
  estar: {
    presentForms: ['esté', 'estés', 'esté', 'estemos', 'estéis', 'estén'],
    pret3pl: 'estuvieron',
  },
  dar: {
    presentForms: ['dé', 'des', 'dé', 'demos', 'deis', 'den'],
    pret3pl: 'dieron',
  },
  haber: {
    presentForms: ['haya', 'hayas', 'haya', 'hayamos', 'hayáis', 'hayan'],
    pret3pl: 'hubieron',
  },
  saber: {
    presentForms: ['sepa', 'sepas', 'sepa', 'sepamos', 'sepáis', 'sepan'],
    pret3pl: 'supieron',
  },
  caber: { presentStem: 'quep', pret3pl: 'cupieron' },
  ver: { presentStem: 've', participles: ['visto'] },
  tener: { presentStem: 'teng', pret3pl: 'tuvieron' },
  venir: { presentStem: 'veng', pret3pl: 'vinieron' },
  poner: { presentStem: 'pong', pret3pl: 'pusieron', participles: ['puesto'] },
  hacer: { presentStem: 'hag', pret3pl: 'hicieron', participles: ['hecho'] },
  satisfacer: {
    presentStem: 'satisfag',
    pret3pl: 'satisficieron',
    participles: ['satisfecho'],
  },
  decir: { presentStem: 'dig', pret3pl: 'dijeron', participles: ['dicho'] },
  bendecir: { presentStem: 'bendig', pret3pl: 'bendijeron', participles: ['bendecido'] },
  maldecir: { presentStem: 'maldig', pret3pl: 'maldijeron', participles: ['maldecido'] },
  traer: { presentStem: 'traig', pret3pl: 'trajeron' },
  caer: { presentStem: 'caig' },
  salir: { presentStem: 'salg' },
  valer: { presentStem: 'valg' },
  oír: { presentStem: 'oig' },
  poder: { stemChange: 'ue', pret3pl: 'pudieron' },
  querer: { stemChange: 'ie', pret3pl: 'quisieron' },
  andar: { pret3pl: 'anduvieron' },
  reír: {
    presentForms: ['ría', 'rías', 'ría', 'riamos', 'riáis', 'rían'],
    pret3pl: 'rieron',
    participles: ['reído'],
  },
  oler: { presentForms: ['huela', 'huelas', 'huela', 'olamos', 'oláis', 'huelan'] },
  errar: { presentForms: ['yerre', 'yerres', 'yerre', 'erremos', 'erréis', 'yerren'] },
};

// Prefixed compounds conjugate like their base (detener like tener). Listed
// explicitly: suffix matching alone would make mover/llover/volver "compounds"
// of ver.
const IRREGULAR_FAMILIES: ReadonlyArray<readonly [string, ReadonlyArray<string>]> = [
  ['tener', ['de', 'con', 'ob', 'man', 're', 'sos', 'entre', 'abs', 'a', 'contra']],
  ['venir', ['con', 'pre', 'inter', 'pro', 'sobre', 'de', 're', 'sub', 'contra', 'ad']],
  [
    'poner',
    ['com', 'pro', 'su', 'dis', 'ex', 'im', 'o', 'pos', 're', 'super', 'contra', 'de', 'inter', 'pre', 'trans', 'yuxta', 'ante', 'sobre', 'sub'],
  ],
  ['hacer', ['des', 're', 'contra']],
  ['decir', ['pre', 'contra', 'des']],
  ['traer', ['a', 'dis', 'con', 'ex', 'sus', 're', 'sub', 'contra', 'abs']],
  ['caer', ['de', 're']],
  ['salir', ['sobre']],
  ['valer', ['equi']],
  ['ver', ['pre', 're', 'entre']],
  ['oír', ['des']],
  ['andar', ['des']],
  ['reír', ['son', 'f', 'des']],
];

// Irregular participles by suffix, so compounds come along (describir →
// descrito, devolver → devuelto). Checked after IRREGULAR's own participles.
const PARTICIPLE_SUFFIXES: ReadonlyArray<readonly [string, string]> = [
  ['abrir', 'abierto'],
  ['cubrir', 'cubierto'],
  ['scribir', 'scrito'],
  ['morir', 'muerto'],
  ['poner', 'puesto'],
  ['volver', 'vuelto'],
  ['solver', 'suelto'],
  ['hacer', 'hecho'],
  ['imprimir', 'impreso'],
  ['proveer', 'provisto'],
];
const PARTICIPLE_EXACT: Readonly<Record<string, ReadonlyArray<string>>> = {
  romper: ['roto'],
  freír: ['frito', 'freído'],
  predecir: ['predicho'],
  contradecir: ['contradicho'],
};

// -cer/-cir after a vowel normally become -zca (conocer → conozca). These
// don't — they take a plain -z- like the after-consonant verbs (vencer → venza).
const Z_NOT_ZC = new Set(['mecer', 'cocer', 'recocer', 'escocer', 'remecer']);

// Verbs the reverse lookup knows about, with a class flag where needed:
//   :ie :ue :i :ie-i :ue-u   stem-change class
//   :acc                     accented weak vowel (enviar → envíe)
// Irregulars from IRREGULAR are included automatically. Deliberately omits
// verbs whose forms collide with very common non-verbs (coser → "cosa",
// parar/parir → "pare") — see HOMOGRAPHS for the ones we keep and guard.
const KNOWN_VERBS = `
hablar llamar llegar dejar pasar quedar tomar trabajar buscar esperar mirar entrar
tratar usar cambiar ayudar necesitar terminar ganar levantar llevar lograr preguntar
presentar aceptar acabar alcanzar aprovechar bajar bailar besar borrar callar
caminar cantar casar celebrar cenar comprar contestar cortar crear cruzar cuidar
dudar durar echar enseñar escuchar estudiar evitar explicar firmar formar fumar
gastar gritar guardar gustar importar intentar invitar lanzar lavar limpiar llorar
luchar mandar marcar matar mejorar olvidar ordenar organizar pagar participar
pelear pintar practicar preparar prestar quitar realizar regresar respirar robar
saltar salvar sacar secar señalar tardar tirar tocar visitar viajar votar abrazar
acercar acompañar admirar adivinar agarrar agradar alejar amar apagar apoyar
arreglar arrastrar asustar atacar atrapar avisar bañar brillar burlar calmar
cargar castigar cazar chocar cocinar colocar conservar considerar copiar dañar
declarar dedicar denunciar desear destacar dibujar disparar disfrutar empujar
encantar enfadar engañar enojar entregar equivocar escapar estallar examinar faltar
felicitar fijar funcionar girar golpear gozar heredar imaginar indicar informar
juntar jurar lamentar liberar limitar llenar manejar nadar notar observar ocupar
odiar pasear pecar pegar perdonar pesar planear platicar preocupar provocar
publicar quemar rechazar regalar rezar rodear saludar sospechar superar utilizar
valorar verificar apreciar anunciar pronunciar renunciar negociar iniciar envidiar
remediar averiguar acostumbrar alegrar apretar:ie arrancar asomar atar aterrizar
comunicar conversar cuestionar descansar desmayar encargar entusiasmar expresar
fracasar ignorar inventar jalar mencionar molestar murmurar ocultar pisar quejar
recuperar repasar retirar sollozar sonar:ue suspirar temblar:ie tropezar:ie
aullar:acc
pensar:ie cerrar:ie comenzar:ie empezar:ie confesar:ie despertar:ie negar:ie
sentar:ie atravesar:ie calentar:ie gobernar:ie manifestar:ie merendar:ie nevar:ie
recomendar:ie regar:ie sembrar:ie encerrar:ie enterrar:ie
contar:ue costar:ue encontrar:ue mostrar:ue demostrar:ue probar:ue recordar:ue
soñar:ue volar:ue acostar:ue acordar:ue almorzar:ue aprobar:ue comprobar:ue
renovar:ue rodar:ue tostar:ue forzar:ue esforzar:ue colgar:ue rogar:ue soltar:ue
apostar:ue jugar:ue
enviar:acc continuar:acc confiar:acc guiar:acc criar:acc vaciar:acc variar:acc
esquiar:acc ampliar:acc enfriar:acc actuar:acc graduar:acc situar:acc evaluar:acc
acentuar:acc
comer beber correr aprender comprender vender leer creer meter prometer responder
romper temer deber esconder sorprender suceder ofender poseer proteger recoger coger
escoger conocer parecer merecer nacer crecer ofrecer agradecer aparecer desaparecer
obedecer pertenecer permanecer establecer reconocer favorecer padecer enloquecer
oscurecer amanecer anochecer envejecer convencer vencer ejercer cometer someter
depender emprender proceder conceder ceder recorrer socorrer mecer
entender:ie perder:ie defender:ie encender:ie atender:ie extender:ie tender:ie
volver:ue devolver:ue envolver:ue resolver:ue mover:ue llover:ue doler:ue
morder:ue soler:ue torcer:ue cocer:ue
vivir escribir abrir recibir decidir subir cumplir permitir existir insistir
discutir sufrir unir compartir describir descubrir cubrir dividir imprimir ocurrir
partir repartir asistir resistir admitir añadir aplaudir confundir consumir convivir
interrumpir sobrevivir suprimir surgir dirigir exigir fingir
prohibir:acc reunir:acc
corregir:i elegir:i pedir:i servir:i repetir:i seguir:i conseguir:i perseguir:i
vestir:i medir:i despedir:i impedir:i competir:i gemir:i rendir:i
sentir:ie-i mentir:ie-i preferir:ie-i sugerir:ie-i convertir:ie-i divertir:ie-i
advertir:ie-i herir:ie-i referir:ie-i requerir:ie-i consentir:ie-i arrepentir:ie-i
hervir:ie-i invertir:ie-i
dormir:ue-u morir:ue-u adquirir:ie
construir destruir huir incluir concluir contribuir distribuir sustituir influir
excluir producir conducir traducir reducir introducir deducir lucir distinguir
extinguir
`;

// Forms with a common non-verb (or different-verb) reading. The post-pass
// never auto-tags these, and an uncertain model tag on one stays
// `possible_subjunctive` rather than being promoted. Collisions between two
// KNOWN_VERBS (sentar/sentir → "sienta", crear/creer → "crea") are detected
// automatically; this list is the non-verb readings a generator can't see.
const HOMOGRAPHS = new Set([
  'coma', 'comas', 'vaya', 'venga', 'oiga', 'cante', 'cantes', 'entre', 'sobre',
  'sobres', 'fuera', 'viaje', 'viajes', 'baile', 'bailes', 'pase', 'pases', 'cobre',
  'venda', 'vendas', 'prenda', 'prendas', 'tema', 'temas', 'toque', 'toques',
  'choque', 'choques', 'ataque', 'ataques', 'calle', 'calles', 'corte', 'cortes',
  'porte', 'portes', 'base', 'bases', 'lance', 'cruce', 'cruces', 'alcance', 'avance',
  'avances', 'enlace', 'goce', 'roce', 'pese', 'vista', 'vistas', 'firme', 'firmes',
  'mate', 'saque', 'cierre', 'cierres', 'meta', 'metas', 'una', 'unas', 'escriba',
  'ría', 'rías', 'fría', 'frías', 'informe', 'informes', 'importe', 'importes',
  'nieve', 'pare', 'pares', 'sale', 'sales', 'cese', 'conforme', 'tarde', 'tardes',
  'levante', 'presente', 'presentes', 'salve', 'dispares', 'escape', 'alegre',
  'alegres', 'arranque', 'cometa', 'cometas', 'tienda', 'tiendas', 'suela', 'suelas',
]);

// ===== Normalisation =====

const LETTERS = /[a-záéíóúüñ]+/g;

function words(span: string): string[] {
  return span.toLowerCase().match(LETTERS) ?? [];
}

// Leading material the model sometimes includes in a verb span: negation and
// proclitic pronouns ("No me digas", "que te vaya").
const SPAN_PREFIX = new Set(['no', 'me', 'te', 'se', 'nos', 'os', 'le', 'les', 'lo', 'la', 'los', 'las', 'que']);

// The verb words of a span, with leading negation/clitics stripped.
function verbWords(span: string): string[] {
  const ws = words(span);
  while (ws.length > 1 && SPAN_PREFIX.has(ws[0]!)) ws.shift();
  return ws;
}

// "recuperarse" → "recuperar"; trims, lowercases. Returns null for anything
// that isn't shaped like an infinitive.
export function normalizeLemma(raw: string): string | null {
  let l = raw.trim().toLowerCase();
  if (/(ar|er|ir|ír)se$/.test(l)) l = l.slice(0, -2);
  return /^[a-záéíóúüñ]*(ar|er|ir|ír)$/.test(l) ? l : null;
}

function verbClass(lemma: string): 'ar' | 'er' | 'ir' {
  if (lemma.endsWith('ar')) return 'ar';
  if (lemma.endsWith('er')) return 'er';
  return 'ir';
}

// ===== Spec lookup =====

function prefixed(prefix: string, e: IrregularEntry): IrregularEntry {
  return {
    ...(e.stemChange ? { stemChange: e.stemChange } : {}),
    ...(e.presentStem ? { presentStem: prefix + e.presentStem } : {}),
    ...(e.presentForms ? { presentForms: e.presentForms.map((f) => prefix + f) } : {}),
    ...(e.pret3pl ? { pret3pl: prefix + e.pret3pl } : {}),
    ...(e.participles ? { participles: e.participles.map((p) => prefix + p) } : {}),
  };
}

function irregularEntry(lemma: string): IrregularEntry | null {
  const exact = IRREGULAR[lemma];
  if (exact) return exact;
  for (const [base, prefixes] of IRREGULAR_FAMILIES) {
    if (!lemma.endsWith(base)) continue;
    const prefix = lemma.slice(0, -base.length);
    if (prefixes.includes(prefix)) return prefixed(prefix, IRREGULAR[base]!);
  }
  return null;
}

let knownFlags: Map<string, string> | null = null;
function knownVerbFlags(): Map<string, string> {
  if (knownFlags) return knownFlags;
  knownFlags = new Map();
  for (const tok of KNOWN_VERBS.split(/\s+/)) {
    if (!tok) continue;
    const [lemma, flag] = tok.split(':');
    knownFlags.set(lemma!, flag ?? '');
  }
  for (const l of Object.keys(IRREGULAR)) if (!knownFlags.has(l)) knownFlags.set(l, '');
  return knownFlags;
}

export function isKnownLemma(lemma: string): boolean {
  return knownVerbFlags().has(lemma);
}

function specFromFlag(lemma: string, flag: string): VerbSpec {
  const irr = irregularEntry(lemma);
  const stemChange: StemChange =
    flag === 'ie' || flag === 'ue' || flag === 'i' || flag === 'ie-i' || flag === 'ue-u'
      ? flag
      : (irr?.stemChange ?? 'none');
  return { ...irr, lemma, stemChange, accented: flag === 'acc' };
}

// Every spec worth trying for a lemma. Known lemmas have exactly one. For a
// lemma we've never seen, we don't know its stem-change class, so we try all of
// them: a correct tag on an unknown stem-changer then survives the veto, while
// a token no class could produce (portas, recuperó) still fails it.
function specsFor(lemma: string): VerbSpec[] {
  const flag = knownVerbFlags().get(lemma);
  if (flag !== undefined) return [specFromFlag(lemma, flag)];
  if (irregularEntry(lemma)) return [specFromFlag(lemma, '')];
  const cls = verbClass(lemma);
  const classes: StemChange[] =
    cls === 'ir' ? ['none', 'ie', 'ue', 'i', 'ie-i', 'ue-u'] : ['none', 'ie', 'ue'];
  const specs: VerbSpec[] = classes.map((c) => ({ lemma, stemChange: c, accented: false }));
  specs.push({ lemma, stemChange: 'none', accented: true });
  return specs;
}

// ===== Stem helpers =====

function replaceLast(stem: string, from: RegExp, to: string): string {
  let idx = -1;
  for (let i = stem.length - 1; i >= 0; i--) {
    if (from.test(stem[i]!)) {
      idx = i;
      break;
    }
  }
  return idx < 0 ? stem : stem.slice(0, idx) + to + stem.slice(idx + 1);
}

// Stem change in the stressed ("boot") forms: 1sg, 2sg, 3sg, 3pl.
function bootChange(stem: string, sc: StemChange): string {
  switch (sc) {
    case 'none':
      return stem;
    case 'ie':
    case 'ie-i':
      // adquirir / inquirir: the changing vowel is i, not e.
      return /e/.test(stem) ? replaceLast(stem, /e/, 'ie') : replaceLast(stem, /i/, 'ie');
    case 'ue':
    case 'ue-u':
      // jugar is the lone u → ue verb.
      return /o/.test(stem) ? replaceLast(stem, /o/, 'ue') : replaceLast(stem, /u/, 'ue');
    case 'i':
      return replaceLast(stem, /e/, 'i');
  }
}

// -ir stem-changers also change in nosotros/vosotros (sintamos, durmamos,
// pidamos) and in the 3rd-person preterite (sintieron, durmieron).
function weakChange(stem: string, sc: StemChange): string {
  if (sc === 'i' || sc === 'ie-i') return replaceLast(stem, /e/, 'i');
  if (sc === 'ue-u') return replaceLast(stem, /o/, 'u');
  return stem;
}

function accentWeakVowel(stem: string): string {
  for (let i = stem.length - 1; i >= 0; i--) {
    const c = stem[i];
    if (c === 'i' || c === 'u') return stem.slice(0, i) + (c === 'i' ? 'í' : 'ú') + stem.slice(i + 1);
  }
  return stem;
}

// Spelling changes that keep the stem's sound before the subjunctive endings.
function orthography(stem: string, lemma: string): string {
  const cls = verbClass(lemma);
  if (cls === 'ar') {
    if (stem.endsWith('gu')) return stem.slice(0, -2) + 'gü'; // averiguar → averigüe
    if (stem.endsWith('c')) return stem.slice(0, -1) + 'qu'; // buscar → busque
    if (stem.endsWith('g')) return stem + 'u'; // llegar → llegue
    if (stem.endsWith('z')) return stem.slice(0, -1) + 'c'; // cruzar → cruce
    return stem;
  }
  if (stem.endsWith('gu') && lemma.endsWith('guir')) return stem.slice(0, -1); // seguir → siga
  if (stem.endsWith('qu') && lemma.endsWith('quir')) return stem.slice(0, -2) + 'c';
  if (stem.endsWith('g')) return stem.slice(0, -1) + 'j'; // coger → coja
  if (stem.endsWith('c')) {
    const before = stem[stem.length - 2] ?? '';
    const afterVowel = /[aeiouáéíóú]/.test(before);
    return stem.slice(0, -1) + (afterVowel && !Z_NOT_ZC.has(lemma) ? 'zc' : 'z');
  }
  if (lemma.endsWith('uir') && !/[gq]uir$/.test(lemma)) return stem + 'y'; // construir → construya
  return stem;
}

// ===== Generation =====

const AR_PRESENT = ['e', 'es', 'e', 'emos', 'éis', 'en'];
const ER_PRESENT = ['a', 'as', 'a', 'amos', 'áis', 'an'];

function presentSubjunctive(spec: VerbSpec): string[] {
  if (spec.presentForms) return [...spec.presentForms];
  const endings = verbClass(spec.lemma) === 'ar' ? AR_PRESENT : ER_PRESENT;
  const base = spec.lemma.slice(0, -2);
  return PERSONS.map((p, i) => {
    if (spec.presentStem) return spec.presentStem + endings[i]!;
    const boot = p !== '1pl' && p !== '2pl';
    let stem = boot
      ? bootChange(base, spec.stemChange)
      : verbClass(spec.lemma) === 'ir'
        ? weakChange(base, spec.stemChange)
        : base;
    if (spec.accented && boot) stem = accentWeakVowel(stem);
    return orthography(stem, spec.lemma) + endings[i]!;
  });
}

function preterite3pl(spec: VerbSpec): string {
  if (spec.pret3pl) return spec.pret3pl;
  const cls = verbClass(spec.lemma);
  let stem = spec.lemma.slice(0, -2);
  if (cls === 'ar') return stem + 'aron';
  if (spec.lemma.endsWith('ducir')) return stem.slice(0, -1) + 'jeron'; // conducir → condujeron
  if (cls === 'ir') stem = weakChange(stem, spec.stemChange);
  if (/[aeo]$/.test(stem) || (/u$/.test(stem) && !/[gq]u$/.test(stem))) {
    return stem + 'yeron'; // leyeron, construyeron
  }
  if (/(ñ|ll)$/.test(stem)) return stem + 'eron'; // gruñeron
  return stem + 'ieron';
}

const STRESS: Readonly<Record<string, string>> = { a: 'á', e: 'é', i: 'í', o: 'ó', u: 'ú' };

function imperfectSubjunctive(spec: VerbSpec, kind: 'ra' | 'se'): string[] {
  const base = preterite3pl(spec).slice(0, -3); // hablaron → habla
  const stressed = base.slice(0, -1) + (STRESS[base.slice(-1)] ?? base.slice(-1));
  // -ra: ra ras ra ramos rais ran; -se: se ses se semos seis sen.
  const s = kind === 'ra' ? 'ra' : 'se';
  return [
    `${base}${s}`,
    `${base}${s}s`,
    `${base}${s}`,
    `${stressed}${s}mos`,
    `${base}${kind === 'ra' ? 'rais' : 'seis'}`,
    `${base}${s}n`,
  ];
}

export function participlesOf(lemma: string): string[] {
  const exact = PARTICIPLE_EXACT[lemma];
  if (exact) return [...exact];
  const irr = irregularEntry(lemma);
  if (irr?.participles) return [...irr.participles];
  if (lemma === 'bendecir' || lemma === 'maldecir') return [lemma.slice(0, -2) + 'ido'];
  for (const [suffix, part] of PARTICIPLE_SUFFIXES) {
    if (lemma.endsWith(suffix)) return [lemma.slice(0, -suffix.length) + part];
  }
  const stem = lemma.slice(0, -2);
  if (verbClass(lemma) === 'ar') return [stem + 'ado'];
  return [/[aeo]$/.test(stem) ? stem + 'ído' : stem + 'ido'];
}

// Every single-word subjunctive form of a lemma (present, imperfect -ra/-se).
// Compound tenses are two words and are matched separately (matchSubjunctive).
export function subjunctiveForms(rawLemma: string): SubjForm[] {
  const lemma = normalizeLemma(rawLemma);
  if (!lemma) return [];
  const out: SubjForm[] = [];
  const seen = new Set<string>();
  for (const spec of specsFor(lemma)) {
    const tables: ReadonlyArray<readonly [SubjTense, string[]]> = [
      ['present', presentSubjunctive(spec)],
      ['imperfect-ra', imperfectSubjunctive(spec, 'ra')],
      ['imperfect-se', imperfectSubjunctive(spec, 'se')],
    ];
    for (const [tense, forms] of tables) {
      forms.forEach((form, i) => {
        const key = `${form}|${tense}|${i}`;
        if (seen.has(key)) return;
        seen.add(key);
        out.push({ form, lemma, tense, person: PERSONS[i]! });
      });
    }
  }
  return out;
}

const COMPOUND_TENSE: Readonly<Partial<Record<SubjTense, SubjTense>>> = {
  present: 'perfect',
  'imperfect-ra': 'pluperfect-ra',
  'imperfect-se': 'pluperfect-se',
};

function collect(matches: ReadonlyArray<SubjForm>): SubjMatch | null {
  const first = matches[0];
  if (!first) return null;
  // If one token is two different tenses at once (never happens for a single
  // lemma in practice), report the first; persons are merged within it.
  const same = matches.filter((m) => m.tense === first.tense);
  return {
    lemma: first.lemma,
    tense: first.tense,
    persons: [...new Set(same.map((m) => m.person))],
  };
}

// Is `span` a subjunctive form of `lemma`? Handles one-word forms and the
// compound tenses (haber in the subjunctive + a participle of the lemma). The
// comparison is accent-sensitive: "hable" and "hablé" are different words.
export function matchSubjunctive(span: string, rawLemma: string): SubjMatch | null {
  const lemma = normalizeLemma(rawLemma);
  if (!lemma) return null;
  const ws = verbWords(span);
  if (ws.length === 1) {
    return collect(subjunctiveForms(lemma).filter((f) => f.form === ws[0]));
  }
  if (ws.length === 2) {
    const aux = collect(subjunctiveForms('haber').filter((f) => f.form === ws[0]));
    const tense = aux ? COMPOUND_TENSE[aux.tense] : undefined;
    if (!aux || !tense) return null;
    // The model may name the lexical verb (escribir) or the auxiliary (haber).
    const participleOk =
      participlesOf(lemma).includes(ws[1]!) ||
      (lemma === 'haber' && /(ado|ido|ído|to|cho|so)$/.test(ws[1]!));
    return participleOk ? { lemma, tense, persons: aux.persons } : null;
  }
  return null;
}

// ===== Reverse lookup =====

let reverseIndex: Map<string, SubjForm[]> | null = null;
let indicativeCollisions: Set<string> | null = null;

function buildReverseIndex(): void {
  reverseIndex = new Map();
  indicativeCollisions = new Set();
  const indicative = new Set<string>();
  for (const lemma of knownVerbFlags().keys()) {
    for (const f of subjunctiveForms(lemma)) {
      const list = reverseIndex.get(f.form) ?? [];
      list.push(f);
      reverseIndex.set(f.form, list);
    }
    // Present indicative 2sg…3pl — the only indicative forms that can collide
    // with another verb's subjunctive (sienta: sentar indicative / sentir
    // subjunctive). Irregular present tables are skipped; none of them collide.
    const spec = specFromFlag(lemma, knownVerbFlags().get(lemma) ?? '');
    if (spec.presentForms || spec.presentStem) continue;
    const cls = verbClass(lemma);
    const base = lemma.slice(0, -2);
    const endings =
      cls === 'ar'
        ? ['as', 'a', 'amos', 'áis', 'an']
        : cls === 'er'
          ? ['es', 'e', 'emos', 'éis', 'en']
          : ['es', 'e', 'imos', 'ís', 'en'];
    endings.forEach((end, i) => {
      const boot = i !== 2 && i !== 3;
      let stem = boot ? bootChange(base, spec.stemChange) : base;
      if (spec.accented && boot) stem = accentWeakVowel(stem);
      indicative.add(stem + end);
    });
  }
  for (const form of reverseIndex.keys()) {
    if (indicative.has(form)) indicativeCollisions.add(form);
  }
}

// All subjunctive analyses of a single token among KNOWN_VERBS. Empty when the
// token isn't a known subjunctive form.
export function analyzeToken(token: string): SubjForm[] {
  if (!reverseIndex) buildReverseIndex();
  return reverseIndex!.get(token.toLowerCase()) ?? [];
}

export function isHomograph(token: string): boolean {
  if (!indicativeCollisions) buildReverseIndex();
  const t = token.toLowerCase();
  return HOMOGRAPHS.has(t) || indicativeCollisions!.has(t);
}

// An analysis the lexicon will stand behind with no model input: a known
// subjunctive form, not a homograph, one tense. Several lemmas are fine as
// long as they agree on tense (fuera: ser or ir, both imperfect).
export function unambiguousAnalysis(token: string): SubjMatch | null {
  if (isHomograph(token)) return null;
  const all = analyzeToken(token);
  const first = all[0];
  if (!first || all.some((a) => a.tense !== first.tense)) return null;
  const lemmas = [...new Set(all.map((a) => a.lemma))];
  return {
    lemma: lemmas.join(' / '),
    tense: first.tense,
    persons: [...new Set(all.map((a) => a.person))],
  };
}

// ===== Human-readable descriptions =====

const TENSE_LABEL: Readonly<Record<SubjTense, string>> = {
  present: 'present subjunctive',
  'imperfect-ra': 'imperfect subjunctive (-ra form)',
  'imperfect-se': 'imperfect subjunctive (-se form)',
  perfect: 'present perfect subjunctive',
  'pluperfect-ra': 'pluperfect subjunctive (-ra form)',
  'pluperfect-se': 'pluperfect subjunctive (-se form)',
};

const PERSON_LABEL: Readonly<Record<PersonNumber, string>> = {
  '1sg': '1st person singular',
  '2sg': '2nd person singular',
  '3sg': '3rd person singular',
  '1pl': '1st person plural',
  '2pl': '2nd person plural',
  '3pl': '3rd person plural',
};

export function describeMatch(m: SubjMatch): string {
  const persons = m.persons.map((p) => PERSON_LABEL[p]).join(' or ');
  return `${m.lemma}, ${TENSE_LABEL[m.tense]}, ${persons}`;
}

export function isPastTense(t: SubjTense): boolean {
  return t !== 'present' && t !== 'perfect';
}

// ===== Pre-scan for gloss facts (item 5) =====

export interface LexiconFact {
  readonly token: string;
  readonly match: SubjMatch;
}

// Distinct tokens in `text` the lexicon identifies unambiguously as
// subjunctive. Handed to the gloss prompt as given facts, so a correctly
// highlighted "aullaran" can't be glossed as the future "aullarán".
export function scanLexiconFacts(text: string): LexiconFact[] {
  const facts: LexiconFact[] = [];
  const seen = new Set<string>();
  for (const w of text.match(/[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+/g) ?? []) {
    const t = w.toLowerCase();
    if (seen.has(t)) continue;
    seen.add(t);
    const match = unambiguousAnalysis(t);
    if (match) facts.push({ token: w, match });
  }
  return facts;
}

export function formatLexiconFacts(facts: ReadonlyArray<LexiconFact>): string {
  return facts.map((f) => `- "${f.token}": ${describeMatch(f.match)}`).join('\n');
}

// ===== Post-pass over resolved model annotations =====

export type MoodRole = 'trigger' | 'subjunctive_verb' | 'possible_subjunctive';

export interface CandidateAnnotation {
  readonly start: number;
  readonly end: number;
  readonly role: MoodRole;
  readonly pairId: number;
  readonly lemma?: string;
}

export interface CheckedAnnotation {
  readonly start: number;
  readonly end: number;
  readonly role: MoodRole;
  readonly pairId: number;
  readonly lemma?: string;
  readonly tense?: SubjTense;
}

// A case where the model's reading and the lexicon's differ. Written to the
// mood review log (never silently resolved in the data the reader can't see):
// recurring disagreement on one lemma means that lexicon entry needs an audit.
export interface LexiconDisagreement {
  readonly lemma: string;
  readonly token: string;
  readonly lexiconAnswer: string;
  readonly modelAnswer: string;
}

// Apply the lexicon to one chunk's annotations:
//   - Veto (item 4): every verb tag must be a subjunctive form of the lemma
//     the model named, or it's dropped — confident tags included, since the
//     observed errors (se recuperó, portas) came through as confident.
//   - Uncertain tags (item 3): promoted to subjunctive_verb when the token is
//     an unambiguous form, kept as possible_subjunctive when it's a homograph.
//   - Lexicon authority (item 5): an unambiguous known form the model left
//     untagged is tagged anyway, as a solo verb.
//   - Trigger guard (item 1): a trigger with no subjunctive_verb sharing its
//     pairId in this chunk is dropped.
export function applyLexicon(
  tlText: string,
  candidates: ReadonlyArray<CandidateAnnotation>,
): { annotations: CheckedAnnotation[]; disagreements: LexiconDisagreement[] } {
  const disagreements: LexiconDisagreement[] = [];
  const verbs: CheckedAnnotation[] = [];
  for (const a of candidates) {
    if (a.role === 'trigger') continue;
    const span = tlText.slice(a.start, a.end);
    const match = a.lemma ? matchSubjunctive(span, a.lemma) : null;
    if (!match) {
      disagreements.push({
        lemma: a.lemma ?? '',
        token: span,
        lexiconAnswer: a.lemma
          ? `not a subjunctive form of ${a.lemma}`
          : 'no lemma given; cannot verify',
        modelAnswer: a.role === 'subjunctive_verb' ? 'subjunctive' : 'possibly subjunctive',
      });
      continue;
    }
    // A confident tag that passed the veto stays confident. An uncertain one is
    // promoted unless the verb is a single homograph word; compound tenses
    // (haya + participle) are never homographs.
    const vw = verbWords(span);
    const role: MoodRole =
      a.role === 'subjunctive_verb' || vw.length > 1 || !isHomograph(vw[0] ?? '')
        ? 'subjunctive_verb'
        : 'possible_subjunctive';
    verbs.push({ start: a.start, end: a.end, role, pairId: a.pairId, lemma: match.lemma, tense: match.tense });
  }

  // Unambiguous known forms the model didn't tag at all.
  let nextPair = Math.max(0, ...candidates.map((c) => c.pairId)) + 1;
  const re = /[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(tlText)) !== null) {
    const start = m.index;
    const end = start + m[0].length;
    if (verbs.some((v) => start < v.end && v.start < end)) continue;
    const match = unambiguousAnalysis(m[0]);
    if (!match) continue;
    const vetoed = disagreements.some((d) => d.token.toLowerCase().includes(m![0].toLowerCase()));
    if (vetoed) continue;
    disagreements.push({
      lemma: match.lemma,
      token: m[0],
      lexiconAnswer: describeMatch(match),
      modelAnswer: 'not tagged as subjunctive',
    });
    verbs.push({
      start,
      end,
      role: 'subjunctive_verb',
      pairId: nextPair++,
      lemma: match.lemma,
      tense: match.tense,
    });
  }

  const licensed = new Set(verbs.filter((v) => v.role === 'subjunctive_verb').map((v) => v.pairId));
  const triggers: CheckedAnnotation[] = candidates
    .filter((a) => a.role === 'trigger' && licensed.has(a.pairId))
    .map((a) => ({ start: a.start, end: a.end, role: a.role, pairId: a.pairId }));

  const annotations = [...triggers, ...verbs].sort((x, y) => x.start - y.start);
  return { annotations, disagreements };
}
